train:
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  max_depth: 5

data:
  raw_data: data/iris_data_for_feast.csv
  
model:
  model_path: models/iris_model.pkl

gcp:
  project_id: 'rapid-sphinx-473108-u4'  # REPLACE THIS
  bucket_name: 'mlops-course-rapid-sphinx-473108-u4-rkm-w4'    # REPLACE THIS
  
validation:
  min_accuracy: 0.70
  min_samples: 30
  required_columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
