name: 🚀 Deploy to GKE

on:
  push:
    branches:
      - cd_demo

jobs:
  deploy:
    name: 🔄 Deploy to GKE & Comment
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 🧰 Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin,kubectl'

      - name: 📡 Get GKE credentials
        run: |
          gcloud container clusters get-credentials autopilot-demo-gke-cluster --region us-central1 --project rapid-sphinx-473108-u4

      - name: ♻️ Update Kubernetes deployment image
        run: |
          echo "♻️ Updating Kubernetes deployment image..."
          kubectl set image deployment/demo-iris-workload iris-api-sha256-1=us-central1-docker.pkg.dev/rapid-sphinx-473108-u4/my-repo/iris-api:latest --namespace=default
          echo "🚀 Successfully Deployed"

